//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguaPotablePuquereo.Models.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_CLIENTE()
        {
            this.TBL_PAGOS = new HashSet<TBL_PAGOS>();
            this.TBL_DEUDA = new HashSet<TBL_DEUDA>();
        }
    
        public int CLI_ID { get; set; }
        public string CLI_RUT { get; set; }
        public string CLI_NOMBRE { get; set; }
        public string CLI_APELLIDO_PATERNO { get; set; }
        public string CLI_APELLIDO_MATERNO { get; set; }
        public string CLI_COMPLETO { get; set; }
        public Nullable<System.DateTime> CLI_CREADO { get; set; }
        public int CLI_CUENTA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PAGOS> TBL_PAGOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_DEUDA> TBL_DEUDA { get; set; }
    }
}
