//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguaPotablePuquereo.Models.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_LOG
    {
        public int LOG_ID { get; set; }
        public string LOG_ERROR { get; set; }
        public string LOG_INNER { get; set; }
        public System.DateTime LOG_FECHA { get; set; }
    }
}
