//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguaPotablePuquereo.Models.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PAGOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_PAGOS()
        {
            this.TBL_DEUDA = new HashSet<TBL_DEUDA>();
        }
    
        public int PAG_ID { get; set; }
        public int PAG_MONTO { get; set; }
        public int CLI_ID { get; set; }
        public System.DateTime PAG_FECHA { get; set; }
        public bool PAG_VIGENCIA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_DEUDA> TBL_DEUDA { get; set; }
        public virtual TBL_CLIENTE TBL_CLIENTE { get; set; }
    }
}
