//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguaPotablePuquereo.Models.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USUARIO
    {
        public string USU_USUARIO { get; set; }
        public string USU_CONTRASEÑA { get; set; }
    }
}
