//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguaPotablePuquereo.Models.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PAGINAS_ADMINISTRABLES
    {
        public int PADM_ID { get; set; }
        public string PADM_HTML_TEXT { get; set; }
    }
}
