//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguaPotablePuquereo.Models.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ESTADO_CARRO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_ESTADO_CARRO()
        {
            this.TBL_CARRO_COMPRA = new HashSet<TBL_CARRO_COMPRA>();
        }
    
        public int CEST_ID { get; set; }
        public string CEST_NOMBRE { get; set; }
        public bool CEST_VIGENTE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_CARRO_COMPRA> TBL_CARRO_COMPRA { get; set; }
    }
}
