//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguaPotablePuquereo.Models.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CARRO_COMPRA
    {
        public int CAR_ID { get; set; }
        public string CAR_TOKEN { get; set; }
        public int CAR_MONTO { get; set; }
        public int CEST_ESTADO { get; set; }
        public string CAR_CODIGO_AUTORIZACION { get; set; }
        public string CAR_CODIGO_COMERCIO { get; set; }
        public string CAR_ORDEN_COMPRA { get; set; }
    
        public virtual TBL_ESTADO_CARRO TBL_ESTADO_CARRO { get; set; }
    }
}
